DROP TABLE IF EXISTS PROFILE;
DROP TABLE IF EXISTS METER_READING;


CREATE TABLE PROFILE (
  PROFILE_NM CHAR(1) NOT NULL,
  MONTH VARCHAR(50) NOT NULL,
  FRACTION DECIMAL(2,2)NOT NULL,
  created_date DATE,
  updated_date DATE );
  
  
CREATE TABLE METER_READING (
  METER_ID INT NOT NULL,
  PROFILE_NM CHAR(1),
  MONTH VARCHAR(100) NOT NULL,
  READING INT NOT NULL,
  CONSUMPTION INT NOT NULL,
  created_date DATE,
  updated_date DATE );  